function showMatches(obj1, obj2, n)

[~, idx1, idx2] = intersect(obj1.id, obj2.id);

showMatchedFeatures(imread(obj1.file), ...
                    imread(obj2.file), ...
                    [obj1.x(idx1(1:n:end)) -obj1.y(idx1(1:n:end))], ...
                    [obj2.x(idx2(1:n:end)) -obj2.y(idx2(1:n:end))], ...
                    'montage');

end