function trafoParam = ICP4opals(inFiles, noOfTransfParam, fixedPointClouds, planeSearchRadius, uniformSamplingDistance, normalSpaceSampling, maxLeverageSampling, hullVoxelSize, maxDeltaAngle, maxDistance, maxRoughness, redPoi, maxNoIt, plot, subsetRadius, trafoOriginalPointClouds, outputFolder)

msg('O', 'SetLogLevel', 'basic');

% Subsampling
subsamplingPercentPoi  = 10; % default value
normalSubsampling      = false;
maxLeverageSubsampling = false;
if normalSpaceSampling < 100
    subsamplingPercentPoi = normalSpaceSampling;
    normalSubsampling = true;
elseif maxLeverageSampling < 100
    subsamplingPercentPoi = maxLeverageSampling;
    maxLeverageSubsampling = true;
end

trafoParam = ICP('InFiles'                 , inFiles, ...
                 'NoOfTransfParam'         , noOfTransfParam, ...
                 'FixedPointClouds'        , fixedPointClouds, ...
                 'PlaneSearchRadius'       , planeSearchRadius, ...
                 'UniformSamplingDistance' , uniformSamplingDistance, ...
                 'HullVoxelSize'           , hullVoxelSize, ...
                 'MaxDeltaAngle'           , maxDeltaAngle, ...
                 'MaxDistance'             , maxDistance, ...
                 'MaxRoughness'            , maxRoughness, ...
                 'RedPoi'                  , redPoi, ...
                 'MaxNoIt'                 , maxNoIt, ...
                 'Plot'                    , plot, ...
                 'SubsetRadius'            , subsetRadius, ...
                 'NormalSubsampling'       , normalSubsampling, ...
                 'MaxLeverageSubsampling'  , maxLeverageSubsampling, ...
                 'SubsamplingPercentPoi'   , subsamplingPercentPoi, ...
                 'TrafoOriginalPointClouds', trafoOriginalPointClouds, ...
                 'OutputFolder'            , outputFolder);          
    
end

% Check dependencies
% [fList,pList] = matlab.codetools.requiredFilesAndProducts('ICP4opals.m');
% for i = 1:numel(fList), fprintf(1, '%s\n', fList{i}), end
